package entity;
// Generated Sep 3, 2019 7:58:03 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;

/**
 * Banners generated by hbm2java
 */
public class Banners  implements java.io.Serializable {


     private int bannerId;
     private Catagories catagories;
     private String bannerName;
     private String bannerDescription;
     private String bannerImage;
     private boolean size;
     private Date created;
     private boolean isDisabled;

    public Banners() {
    }

	
    public Banners(int bannerId, Catagories catagories, String bannerName, String bannerImage, boolean size, Date created, boolean isDisabled) {
        this.bannerId = bannerId;
        this.catagories = catagories;
        this.bannerName = bannerName;
        this.bannerImage = bannerImage;
        this.size = size;
        this.created = created;
        this.isDisabled = isDisabled;
    }
    public Banners(int bannerId, Catagories catagories, String bannerName, String bannerDescription, String bannerImage, boolean size, Date created, boolean isDisabled) {
       this.bannerId = bannerId;
       this.catagories = catagories;
       this.bannerName = bannerName;
       this.bannerDescription = bannerDescription;
       this.bannerImage = bannerImage;
       this.size = size;
       this.created = created;
       this.isDisabled = isDisabled;
    }
   
    public int getBannerId() {
        return this.bannerId;
    }
    
    public void setBannerId(int bannerId) {
        this.bannerId = bannerId;
    }
    public Catagories getCatagories() {
        return this.catagories;
    }
    
    public void setCatagories(Catagories catagories) {
        this.catagories = catagories;
    }
    public String getBannerName() {
        return this.bannerName;
    }
    
    public void setBannerName(String bannerName) {
        this.bannerName = bannerName;
    }
    public String getBannerDescription() {
        return this.bannerDescription;
    }
    
    public void setBannerDescription(String bannerDescription) {
        this.bannerDescription = bannerDescription;
    }
    public String getBannerImage() {
        return this.bannerImage;
    }
    
    public void setBannerImage(String bannerImage) {
        this.bannerImage = bannerImage;
    }
    public boolean isSize() {
        return this.size;
    }
    
    public void setSize(boolean size) {
        this.size = size;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public boolean isIsDisabled() {
        return this.isDisabled;
    }
    
    public void setIsDisabled(boolean isDisabled) {
        this.isDisabled = isDisabled;
    }




}


