package entity;
// Generated Sep 3, 2019 7:58:03 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Catagories generated by hbm2java
 */
public class Catagories  implements java.io.Serializable {


     private int catagoryId;
     private String catagoryName;
     private Integer catagoryPriority;
     private Integer parentId;
     private Date created;
     private boolean isDisabled;
     private Set productses = new HashSet(0);
     private Set bannerses = new HashSet(0);

    public Catagories() {
    }

	
    public Catagories(int catagoryId, String catagoryName, Date created, boolean isDisabled) {
        this.catagoryId = catagoryId;
        this.catagoryName = catagoryName;
        this.created = created;
        this.isDisabled = isDisabled;
    }
    public Catagories(int catagoryId, String catagoryName, Integer catagoryPriority, Integer parentId, Date created, boolean isDisabled, Set productses, Set bannerses) {
       this.catagoryId = catagoryId;
       this.catagoryName = catagoryName;
       this.catagoryPriority = catagoryPriority;
       this.parentId = parentId;
       this.created = created;
       this.isDisabled = isDisabled;
       this.productses = productses;
       this.bannerses = bannerses;
    }
   
    public int getCatagoryId() {
        return this.catagoryId;
    }
    
    public void setCatagoryId(int catagoryId) {
        this.catagoryId = catagoryId;
    }
    public String getCatagoryName() {
        return this.catagoryName;
    }
    
    public void setCatagoryName(String catagoryName) {
        this.catagoryName = catagoryName;
    }
    public Integer getCatagoryPriority() {
        return this.catagoryPriority;
    }
    
    public void setCatagoryPriority(Integer catagoryPriority) {
        this.catagoryPriority = catagoryPriority;
    }
    public Integer getParentId() {
        return this.parentId;
    }
    
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public boolean isIsDisabled() {
        return this.isDisabled;
    }
    
    public void setIsDisabled(boolean isDisabled) {
        this.isDisabled = isDisabled;
    }
    public Set getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set productses) {
        this.productses = productses;
    }
    public Set getBannerses() {
        return this.bannerses;
    }
    
    public void setBannerses(Set bannerses) {
        this.bannerses = bannerses;
    }




}


