package entity;
// Generated Sep 3, 2019 7:58:03 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cities generated by hbm2java
 */
public class Cities  implements java.io.Serializable {


     private int cityId;
     private String cityName;
     private int distance;
     private Date created;
     private boolean isDisabled;
     private Set orderses = new HashSet(0);
     private Set userses = new HashSet(0);

    public Cities() {
    }

	
    public Cities(int cityId, int distance, Date created, boolean isDisabled) {
        this.cityId = cityId;
        this.distance = distance;
        this.created = created;
        this.isDisabled = isDisabled;
    }
    public Cities(int cityId, String cityName, int distance, Date created, boolean isDisabled, Set orderses, Set userses) {
       this.cityId = cityId;
       this.cityName = cityName;
       this.distance = distance;
       this.created = created;
       this.isDisabled = isDisabled;
       this.orderses = orderses;
       this.userses = userses;
    }
   
    public int getCityId() {
        return this.cityId;
    }
    
    public void setCityId(int cityId) {
        this.cityId = cityId;
    }
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }
    public int getDistance() {
        return this.distance;
    }
    
    public void setDistance(int distance) {
        this.distance = distance;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public boolean isIsDisabled() {
        return this.isDisabled;
    }
    
    public void setIsDisabled(boolean isDisabled) {
        this.isDisabled = isDisabled;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }




}


