package entity;
// Generated Sep 3, 2019 7:58:03 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrderStatus generated by hbm2java
 */
public class OrderStatus  implements java.io.Serializable {


     private int orderStatusId;
     private String orderStatusName;
     private Date created;
     private boolean isDisabled;
     private Set orderses = new HashSet(0);

    public OrderStatus() {
    }

	
    public OrderStatus(int orderStatusId, Date created, boolean isDisabled) {
        this.orderStatusId = orderStatusId;
        this.created = created;
        this.isDisabled = isDisabled;
    }
    public OrderStatus(int orderStatusId, String orderStatusName, Date created, boolean isDisabled, Set orderses) {
       this.orderStatusId = orderStatusId;
       this.orderStatusName = orderStatusName;
       this.created = created;
       this.isDisabled = isDisabled;
       this.orderses = orderses;
    }
   
    public int getOrderStatusId() {
        return this.orderStatusId;
    }
    
    public void setOrderStatusId(int orderStatusId) {
        this.orderStatusId = orderStatusId;
    }
    public String getOrderStatusName() {
        return this.orderStatusName;
    }
    
    public void setOrderStatusName(String orderStatusName) {
        this.orderStatusName = orderStatusName;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public boolean isIsDisabled() {
        return this.isDisabled;
    }
    
    public void setIsDisabled(boolean isDisabled) {
        this.isDisabled = isDisabled;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }




}


