package entity;
// Generated Sep 3, 2019 7:58:03 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * OrderDetail generated by hbm2java
 */
public class OrderDetail  implements java.io.Serializable {


     private OrderDetailId id;
     private Orders orders;
     private Sizes sizes;
     private Products products;
     private int quantity;
     private Double totalPrice;
     private Date created;
     private boolean isDisabled;

    public OrderDetail() {
    }

	
    public OrderDetail(OrderDetailId id, Orders orders, Sizes sizes, Products products, int quantity, Date created, boolean isDisabled) {
        this.id = id;
        this.orders = orders;
        this.sizes = sizes;
        this.products = products;
        this.quantity = quantity;
        this.created = created;
        this.isDisabled = isDisabled;
    }
    public OrderDetail(OrderDetailId id, Orders orders, Sizes sizes, Products products, int quantity, Double totalPrice, Date created, boolean isDisabled) {
       this.id = id;
       this.orders = orders;
       this.sizes = sizes;
       this.products = products;
       this.quantity = quantity;
       this.totalPrice = totalPrice;
       this.created = created;
       this.isDisabled = isDisabled;
    }
   
    public OrderDetailId getId() {
        return this.id;
    }
    
    public void setId(OrderDetailId id) {
        this.id = id;
    }
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }
    public Sizes getSizes() {
        return this.sizes;
    }
    
    public void setSizes(Sizes sizes) {
        this.sizes = sizes;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public Double getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public boolean isIsDisabled() {
        return this.isDisabled;
    }
    
    public void setIsDisabled(boolean isDisabled) {
        this.isDisabled = isDisabled;
    }




}


