package entity;
// Generated Sep 3, 2019 7:58:03 PM by Hibernate Tools 3.6.0



/**
 * OrderDetailId generated by hbm2java
 */
public class OrderDetailId  implements java.io.Serializable {


     private int productId;
     private int orderId;
     private int sizeId;

    public OrderDetailId() {
    }

    public OrderDetailId(int productId, int orderId, int sizeId) {
       this.productId = productId;
       this.orderId = orderId;
       this.sizeId = sizeId;
    }
   
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public int getSizeId() {
        return this.sizeId;
    }
    
    public void setSizeId(int sizeId) {
        this.sizeId = sizeId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrderDetailId) ) return false;
		 OrderDetailId castOther = ( OrderDetailId ) other; 
         
		 return (this.getProductId()==castOther.getProductId())
 && (this.getOrderId()==castOther.getOrderId())
 && (this.getSizeId()==castOther.getSizeId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProductId();
         result = 37 * result + this.getOrderId();
         result = 37 * result + this.getSizeId();
         return result;
   }   


}


