package entity;
// Generated Sep 3, 2019 7:58:03 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private int orderId;
     private Cities cities;
     private OrderStatus orderStatus;
     private Ships ships;
     private Users users;
     private String fullName;
     private String phone;
     private String email;
     private String userAddress;
     private String postcodeOrZip;
     private Double totalPrice;
     private Date created;
     private boolean isDisabled;
     private Set orderDetails = new HashSet(0);

    public Orders() {
    }

	
    public Orders(int orderId, Cities cities, Ships ships, String fullName, String phone, String email, String userAddress, String postcodeOrZip, Date created, boolean isDisabled) {
        this.orderId = orderId;
        this.cities = cities;
        this.ships = ships;
        this.fullName = fullName;
        this.phone = phone;
        this.email = email;
        this.userAddress = userAddress;
        this.postcodeOrZip = postcodeOrZip;
        this.created = created;
        this.isDisabled = isDisabled;
    }
    public Orders(int orderId, Cities cities, OrderStatus orderStatus, Ships ships, Users users, String fullName, String phone, String email, String userAddress, String postcodeOrZip, Double totalPrice, Date created, boolean isDisabled, Set orderDetails) {
       this.orderId = orderId;
       this.cities = cities;
       this.orderStatus = orderStatus;
       this.ships = ships;
       this.users = users;
       this.fullName = fullName;
       this.phone = phone;
       this.email = email;
       this.userAddress = userAddress;
       this.postcodeOrZip = postcodeOrZip;
       this.totalPrice = totalPrice;
       this.created = created;
       this.isDisabled = isDisabled;
       this.orderDetails = orderDetails;
    }
   
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public Cities getCities() {
        return this.cities;
    }
    
    public void setCities(Cities cities) {
        this.cities = cities;
    }
    public OrderStatus getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(OrderStatus orderStatus) {
        this.orderStatus = orderStatus;
    }
    public Ships getShips() {
        return this.ships;
    }
    
    public void setShips(Ships ships) {
        this.ships = ships;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUserAddress() {
        return this.userAddress;
    }
    
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }
    public String getPostcodeOrZip() {
        return this.postcodeOrZip;
    }
    
    public void setPostcodeOrZip(String postcodeOrZip) {
        this.postcodeOrZip = postcodeOrZip;
    }
    public Double getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public boolean isIsDisabled() {
        return this.isDisabled;
    }
    
    public void setIsDisabled(boolean isDisabled) {
        this.isDisabled = isDisabled;
    }
    public Set getOrderDetails() {
        return this.orderDetails;
    }
    
    public void setOrderDetails(Set orderDetails) {
        this.orderDetails = orderDetails;
    }




}


