package entity;
// Generated Sep 3, 2019 7:58:03 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private int productId;
     private Catagories catagories;
     private Brands brands;
     private Sales sales;
     private String productName;
     private double price;
     private String productDescription;
     private Integer bestSeller;
     private Date created;
     private boolean isDisabled;
     private Set sizeses = new HashSet(0);
     private Set productCommentses = new HashSet(0);
     private Set orderDetails = new HashSet(0);
     private Set sliderses = new HashSet(0);
     private Set productImageses = new HashSet(0);
     private Set wishLists = new HashSet(0);

    public Products() {
    }

	
    public Products(int productId, Catagories catagories, String productName, double price, Date created, boolean isDisabled) {
        this.productId = productId;
        this.catagories = catagories;
        this.productName = productName;
        this.price = price;
        this.created = created;
        this.isDisabled = isDisabled;
    }
    public Products(int productId, Catagories catagories, Brands brands, Sales sales, String productName, double price, String productDescription, Integer bestSeller, Date created, boolean isDisabled, Set sizeses, Set productCommentses, Set orderDetails, Set sliderses, Set productImageses, Set wishLists) {
       this.productId = productId;
       this.catagories = catagories;
       this.brands = brands;
       this.sales = sales;
       this.productName = productName;
       this.price = price;
       this.productDescription = productDescription;
       this.bestSeller = bestSeller;
       this.created = created;
       this.isDisabled = isDisabled;
       this.sizeses = sizeses;
       this.productCommentses = productCommentses;
       this.orderDetails = orderDetails;
       this.sliderses = sliderses;
       this.productImageses = productImageses;
       this.wishLists = wishLists;
    }
   
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    public Catagories getCatagories() {
        return this.catagories;
    }
    
    public void setCatagories(Catagories catagories) {
        this.catagories = catagories;
    }
    public Brands getBrands() {
        return this.brands;
    }
    
    public void setBrands(Brands brands) {
        this.brands = brands;
    }
    public Sales getSales() {
        return this.sales;
    }
    
    public void setSales(Sales sales) {
        this.sales = sales;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public String getProductDescription() {
        return this.productDescription;
    }
    
    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }
    public Integer getBestSeller() {
        return this.bestSeller;
    }
    
    public void setBestSeller(Integer bestSeller) {
        this.bestSeller = bestSeller;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public boolean isIsDisabled() {
        return this.isDisabled;
    }
    
    public void setIsDisabled(boolean isDisabled) {
        this.isDisabled = isDisabled;
    }
    public Set getSizeses() {
        return this.sizeses;
    }
    
    public void setSizeses(Set sizeses) {
        this.sizeses = sizeses;
    }
    public Set getProductCommentses() {
        return this.productCommentses;
    }
    
    public void setProductCommentses(Set productCommentses) {
        this.productCommentses = productCommentses;
    }
    public Set getOrderDetails() {
        return this.orderDetails;
    }
    
    public void setOrderDetails(Set orderDetails) {
        this.orderDetails = orderDetails;
    }
    public Set getSliderses() {
        return this.sliderses;
    }
    
    public void setSliderses(Set sliderses) {
        this.sliderses = sliderses;
    }
    public Set getProductImageses() {
        return this.productImageses;
    }
    
    public void setProductImageses(Set productImageses) {
        this.productImageses = productImageses;
    }
    public Set getWishLists() {
        return this.wishLists;
    }
    
    public void setWishLists(Set wishLists) {
        this.wishLists = wishLists;
    }




}


