package entity;
// Generated Sep 3, 2019 7:58:03 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;

/**
 * ProductImages generated by hbm2java
 */
public class ProductImages  implements java.io.Serializable {


     private int imageId;
     private Products products;
     private String link;
     private Date created;
     private boolean isDisabled;

    public ProductImages() {
    }

    public ProductImages(int imageId, Products products, String link, Date created, boolean isDisabled) {
       this.imageId = imageId;
       this.products = products;
       this.link = link;
       this.created = created;
       this.isDisabled = isDisabled;
    }
   
    public int getImageId() {
        return this.imageId;
    }
    
    public void setImageId(int imageId) {
        this.imageId = imageId;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public boolean isIsDisabled() {
        return this.isDisabled;
    }
    
    public void setIsDisabled(boolean isDisabled) {
        this.isDisabled = isDisabled;
    }




}


