package entity;
// Generated Sep 3, 2019 7:58:03 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sales generated by hbm2java
 */
public class Sales  implements java.io.Serializable {


     private int saleId;
     private String saleName;
     private int percentage;
     private Date created;
     private boolean isDisabled;
     private Set productses = new HashSet(0);

    public Sales() {
    }

	
    public Sales(int saleId, String saleName, int percentage, Date created, boolean isDisabled) {
        this.saleId = saleId;
        this.saleName = saleName;
        this.percentage = percentage;
        this.created = created;
        this.isDisabled = isDisabled;
    }
    public Sales(int saleId, String saleName, int percentage, Date created, boolean isDisabled, Set productses) {
       this.saleId = saleId;
       this.saleName = saleName;
       this.percentage = percentage;
       this.created = created;
       this.isDisabled = isDisabled;
       this.productses = productses;
    }
   
    public int getSaleId() {
        return this.saleId;
    }
    
    public void setSaleId(int saleId) {
        this.saleId = saleId;
    }
    public String getSaleName() {
        return this.saleName;
    }
    
    public void setSaleName(String saleName) {
        this.saleName = saleName;
    }
    public int getPercentage() {
        return this.percentage;
    }
    
    public void setPercentage(int percentage) {
        this.percentage = percentage;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public boolean isIsDisabled() {
        return this.isDisabled;
    }
    
    public void setIsDisabled(boolean isDisabled) {
        this.isDisabled = isDisabled;
    }
    public Set getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set productses) {
        this.productses = productses;
    }




}


