package entity;
// Generated Sep 3, 2019 7:58:03 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ships generated by hbm2java
 */
public class Ships  implements java.io.Serializable {


     private int shipId;
     private int minDistance;
     private int maxDistance;
     private double fee;
     private Date created;
     private boolean isDisabled;
     private Set orderses = new HashSet(0);

    public Ships() {
    }

	
    public Ships(int shipId, int minDistance, int maxDistance, double fee, Date created, boolean isDisabled) {
        this.shipId = shipId;
        this.minDistance = minDistance;
        this.maxDistance = maxDistance;
        this.fee = fee;
        this.created = created;
        this.isDisabled = isDisabled;
    }
    public Ships(int shipId, int minDistance, int maxDistance, double fee, Date created, boolean isDisabled, Set orderses) {
       this.shipId = shipId;
       this.minDistance = minDistance;
       this.maxDistance = maxDistance;
       this.fee = fee;
       this.created = created;
       this.isDisabled = isDisabled;
       this.orderses = orderses;
    }
   
    public int getShipId() {
        return this.shipId;
    }
    
    public void setShipId(int shipId) {
        this.shipId = shipId;
    }
    public int getMinDistance() {
        return this.minDistance;
    }
    
    public void setMinDistance(int minDistance) {
        this.minDistance = minDistance;
    }
    public int getMaxDistance() {
        return this.maxDistance;
    }
    
    public void setMaxDistance(int maxDistance) {
        this.maxDistance = maxDistance;
    }
    public double getFee() {
        return this.fee;
    }
    
    public void setFee(double fee) {
        this.fee = fee;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public boolean isIsDisabled() {
        return this.isDisabled;
    }
    
    public void setIsDisabled(boolean isDisabled) {
        this.isDisabled = isDisabled;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }




}


