package entity;
// Generated Sep 3, 2019 7:58:03 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * ShopInformation generated by hbm2java
 */
public class ShopInformation  implements java.io.Serializable {


     private int shopInformationId;
     private String logoTop;
     private String slogan;
     private String shopImage;
     private String shopDescription;
     private String founderImage;
     private String founderQuote;
     private String contactEmail;
     private String contactPhone;
     private String contactAddress;
     private Date created;
     private boolean isDisabled;
     private String logoBottom;

    public ShopInformation() {
    }

	
    public ShopInformation(int shopInformationId, String logoTop, String slogan, String contactEmail, String contactPhone, String contactAddress, Date created, boolean isDisabled) {
        this.shopInformationId = shopInformationId;
        this.logoTop = logoTop;
        this.slogan = slogan;
        this.contactEmail = contactEmail;
        this.contactPhone = contactPhone;
        this.contactAddress = contactAddress;
        this.created = created;
        this.isDisabled = isDisabled;
    }
    public ShopInformation(int shopInformationId, String logoTop, String slogan, String shopImage, String shopDescription, String founderImage, String founderQuote, String contactEmail, String contactPhone, String contactAddress, Date created, boolean isDisabled, String logoBottom) {
       this.shopInformationId = shopInformationId;
       this.logoTop = logoTop;
       this.slogan = slogan;
       this.shopImage = shopImage;
       this.shopDescription = shopDescription;
       this.founderImage = founderImage;
       this.founderQuote = founderQuote;
       this.contactEmail = contactEmail;
       this.contactPhone = contactPhone;
       this.contactAddress = contactAddress;
       this.created = created;
       this.isDisabled = isDisabled;
       this.logoBottom = logoBottom;
    }
   
    public int getShopInformationId() {
        return this.shopInformationId;
    }
    
    public void setShopInformationId(int shopInformationId) {
        this.shopInformationId = shopInformationId;
    }
    public String getLogoTop() {
        return this.logoTop;
    }
    
    public void setLogoTop(String logoTop) {
        this.logoTop = logoTop;
    }
    public String getSlogan() {
        return this.slogan;
    }
    
    public void setSlogan(String slogan) {
        this.slogan = slogan;
    }
    public String getShopImage() {
        return this.shopImage;
    }
    
    public void setShopImage(String shopImage) {
        this.shopImage = shopImage;
    }
    public String getShopDescription() {
        return this.shopDescription;
    }
    
    public void setShopDescription(String shopDescription) {
        this.shopDescription = shopDescription;
    }
    public String getFounderImage() {
        return this.founderImage;
    }
    
    public void setFounderImage(String founderImage) {
        this.founderImage = founderImage;
    }
    public String getFounderQuote() {
        return this.founderQuote;
    }
    
    public void setFounderQuote(String founderQuote) {
        this.founderQuote = founderQuote;
    }
    public String getContactEmail() {
        return this.contactEmail;
    }
    
    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }
    public String getContactPhone() {
        return this.contactPhone;
    }
    
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }
    public String getContactAddress() {
        return this.contactAddress;
    }
    
    public void setContactAddress(String contactAddress) {
        this.contactAddress = contactAddress;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public boolean isIsDisabled() {
        return this.isDisabled;
    }
    
    public void setIsDisabled(boolean isDisabled) {
        this.isDisabled = isDisabled;
    }
    public String getLogoBottom() {
        return this.logoBottom;
    }
    
    public void setLogoBottom(String logoBottom) {
        this.logoBottom = logoBottom;
    }




}


