package entity;
// Generated Sep 3, 2019 7:58:03 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sizes generated by hbm2java
 */
public class Sizes  implements java.io.Serializable {


     private int sizeId;
     private Products products;
     private String sizeName;
     private int stock;
     private Date created;
     private boolean isDisabled;
     private Set orderDetails = new HashSet(0);

    public Sizes() {
    }

	
    public Sizes(int sizeId, Products products, String sizeName, int stock, Date created, boolean isDisabled) {
        this.sizeId = sizeId;
        this.products = products;
        this.sizeName = sizeName;
        this.stock = stock;
        this.created = created;
        this.isDisabled = isDisabled;
    }
    public Sizes(int sizeId, Products products, String sizeName, int stock, Date created, boolean isDisabled, Set orderDetails) {
       this.sizeId = sizeId;
       this.products = products;
       this.sizeName = sizeName;
       this.stock = stock;
       this.created = created;
       this.isDisabled = isDisabled;
       this.orderDetails = orderDetails;
    }
   
    public int getSizeId() {
        return this.sizeId;
    }
    
    public void setSizeId(int sizeId) {
        this.sizeId = sizeId;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public String getSizeName() {
        return this.sizeName;
    }
    
    public void setSizeName(String sizeName) {
        this.sizeName = sizeName;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public boolean isIsDisabled() {
        return this.isDisabled;
    }
    
    public void setIsDisabled(boolean isDisabled) {
        this.isDisabled = isDisabled;
    }
    public Set getOrderDetails() {
        return this.orderDetails;
    }
    
    public void setOrderDetails(Set orderDetails) {
        this.orderDetails = orderDetails;
    }




}


