package entity;
// Generated Sep 3, 2019 7:58:03 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;

/**
 * Sliders generated by hbm2java
 */
public class Sliders  implements java.io.Serializable {


     private int sliderId;
     private Products products;
     private String title;
     private String subTitle;
     private String content;
     private String imageLink;
     private Date created;
     private boolean isDisabled;

    public Sliders() {
    }

	
    public Sliders(int sliderId, Products products, String imageLink, Date created, boolean isDisabled) {
        this.sliderId = sliderId;
        this.products = products;
        this.imageLink = imageLink;
        this.created = created;
        this.isDisabled = isDisabled;
    }
    public Sliders(int sliderId, Products products, String title, String subTitle, String content, String imageLink, Date created, boolean isDisabled) {
       this.sliderId = sliderId;
       this.products = products;
       this.title = title;
       this.subTitle = subTitle;
       this.content = content;
       this.imageLink = imageLink;
       this.created = created;
       this.isDisabled = isDisabled;
    }
   
    public int getSliderId() {
        return this.sliderId;
    }
    
    public void setSliderId(int sliderId) {
        this.sliderId = sliderId;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getSubTitle() {
        return this.subTitle;
    }
    
    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getImageLink() {
        return this.imageLink;
    }
    
    public void setImageLink(String imageLink) {
        this.imageLink = imageLink;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public boolean isIsDisabled() {
        return this.isDisabled;
    }
    
    public void setIsDisabled(boolean isDisabled) {
        this.isDisabled = isDisabled;
    }




}


