package entity;
// Generated Sep 3, 2019 7:58:03 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;

/**
 * Stores generated by hbm2java
 */
public class Stores  implements java.io.Serializable {


     private int storeId;
     private String storeName;
     private String email;
     private String phone;
     private String storeAddress;
     private Date created;
     private boolean isDisabled;
     private String storeImage;

    public Stores() {
    }

    public Stores(int storeId, String storeName, String email, String phone, String storeAddress, Date created, boolean isDisabled, String storeImage) {
       this.storeId = storeId;
       this.storeName = storeName;
       this.email = email;
       this.phone = phone;
       this.storeAddress = storeAddress;
       this.created = created;
       this.isDisabled = isDisabled;
       this.storeImage = storeImage;
    }
   
    public int getStoreId() {
        return this.storeId;
    }
    
    public void setStoreId(int storeId) {
        this.storeId = storeId;
    }
    public String getStoreName() {
        return this.storeName;
    }
    
    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getStoreAddress() {
        return this.storeAddress;
    }
    
    public void setStoreAddress(String storeAddress) {
        this.storeAddress = storeAddress;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public boolean isIsDisabled() {
        return this.isDisabled;
    }
    
    public void setIsDisabled(boolean isDisabled) {
        this.isDisabled = isDisabled;
    }
    public String getStoreImage() {
        return this.storeImage;
    }
    
    public void setStoreImage(String storeImage) {
        this.storeImage = storeImage;
    }




}


