package entity;
// Generated Sep 3, 2019 7:58:03 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;

/**
 * UserFeedbacks generated by hbm2java
 */
public class UserFeedbacks  implements java.io.Serializable {


     private int feedbackId;
     private Users users;
     private String fullName;
     private String email;
     private String contactTitle;
     private String contactMessage;
     private Date created;
     private boolean isDisabled;

    public UserFeedbacks() {
    }

	
    public UserFeedbacks(int feedbackId, String contactMessage, Date created, boolean isDisabled) {
        this.feedbackId = feedbackId;
        this.contactMessage = contactMessage;
        this.created = created;
        this.isDisabled = isDisabled;
    }
    public UserFeedbacks(int feedbackId, Users users, String fullName, String email, String contactTitle, String contactMessage, Date created, boolean isDisabled) {
       this.feedbackId = feedbackId;
       this.users = users;
       this.fullName = fullName;
       this.email = email;
       this.contactTitle = contactTitle;
       this.contactMessage = contactMessage;
       this.created = created;
       this.isDisabled = isDisabled;
    }
   
    public int getFeedbackId() {
        return this.feedbackId;
    }
    
    public void setFeedbackId(int feedbackId) {
        this.feedbackId = feedbackId;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getContactTitle() {
        return this.contactTitle;
    }
    
    public void setContactTitle(String contactTitle) {
        this.contactTitle = contactTitle;
    }
    public String getContactMessage() {
        return this.contactMessage;
    }
    
    public void setContactMessage(String contactMessage) {
        this.contactMessage = contactMessage;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public boolean isIsDisabled() {
        return this.isDisabled;
    }
    
    public void setIsDisabled(boolean isDisabled) {
        this.isDisabled = isDisabled;
    }




}


