package entity;
// Generated Sep 3, 2019 7:58:03 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private int userId;
     private Cities cities;
     private String userName;
     private String userPassword;
     private String email;
     private String fullName;
     private String phone;
     private String userAddress;
     private Date created;
     private boolean isDisabled;
     private Set productCommentses = new HashSet(0);
     private Set orderses = new HashSet(0);
     private Set userFeedbackses = new HashSet(0);
     private Set wishLists = new HashSet(0);

    public Users() {
    }

	
    public Users(int userId, Cities cities, String userName, String userPassword, String email, Date created, boolean isDisabled) {
        this.userId = userId;
        this.cities = cities;
        this.userName = userName;
        this.userPassword = userPassword;
        this.email = email;
        this.created = created;
        this.isDisabled = isDisabled;
    }
    public Users(int userId, Cities cities, String userName, String userPassword, String email, String fullName, String phone, String userAddress, Date created, boolean isDisabled, Set productCommentses, Set orderses, Set userFeedbackses, Set wishLists) {
       this.userId = userId;
       this.cities = cities;
       this.userName = userName;
       this.userPassword = userPassword;
       this.email = email;
       this.fullName = fullName;
       this.phone = phone;
       this.userAddress = userAddress;
       this.created = created;
       this.isDisabled = isDisabled;
       this.productCommentses = productCommentses;
       this.orderses = orderses;
       this.userFeedbackses = userFeedbackses;
       this.wishLists = wishLists;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public Cities getCities() {
        return this.cities;
    }
    
    public void setCities(Cities cities) {
        this.cities = cities;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getUserAddress() {
        return this.userAddress;
    }
    
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public boolean isIsDisabled() {
        return this.isDisabled;
    }
    
    public void setIsDisabled(boolean isDisabled) {
        this.isDisabled = isDisabled;
    }
    public Set getProductCommentses() {
        return this.productCommentses;
    }
    
    public void setProductCommentses(Set productCommentses) {
        this.productCommentses = productCommentses;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }
    public Set getUserFeedbackses() {
        return this.userFeedbackses;
    }
    
    public void setUserFeedbackses(Set userFeedbackses) {
        this.userFeedbackses = userFeedbackses;
    }
    public Set getWishLists() {
        return this.wishLists;
    }
    
    public void setWishLists(Set wishLists) {
        this.wishLists = wishLists;
    }




}


