package entity;
// Generated Sep 3, 2019 7:58:03 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * WishList generated by hbm2java
 */
public class WishList  implements java.io.Serializable {


     private WishListId id;
     private Users users;
     private Products products;
     private Date created;
     private boolean isDisabled;

    public WishList() {
    }

    public WishList(WishListId id, Users users, Products products, Date created, boolean isDisabled) {
       this.id = id;
       this.users = users;
       this.products = products;
       this.created = created;
       this.isDisabled = isDisabled;
    }
   
    public WishListId getId() {
        return this.id;
    }
    
    public void setId(WishListId id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public boolean isIsDisabled() {
        return this.isDisabled;
    }
    
    public void setIsDisabled(boolean isDisabled) {
        this.isDisabled = isDisabled;
    }




}


