package entity;
// Generated Sep 3, 2019 7:58:03 PM by Hibernate Tools 3.6.0



/**
 * WishListId generated by hbm2java
 */
public class WishListId  implements java.io.Serializable {


     private int productId;
     private int userId;

    public WishListId() {
    }

    public WishListId(int productId, int userId) {
       this.productId = productId;
       this.userId = userId;
    }
   
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof WishListId) ) return false;
		 WishListId castOther = ( WishListId ) other; 
         
		 return (this.getProductId()==castOther.getProductId())
 && (this.getUserId()==castOther.getUserId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProductId();
         result = 37 * result + this.getUserId();
         return result;
   }   


}


